parameters:
  database_host: 3306

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Mark all classes which are inherited from Command with tag `console.command`
    # for further processing in compiler passes(Console\DependencyInjection\Compiler\CommandPass)
    _instanceof:
        Symfony\Component\Console\Command\Command:
            tags: ['console.command']

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Console\:
        resource: '../src/*'
        exclude: '../src/{Exception, DependencyInjection}'

    Console\Utils\ConnectionConfiguration:
        arguments: ['test', 'root', '', 'localhost', 3306]

    Symfony\Component\Console\Application:
        public: true
